const state = {
	accessToken: null,
	advancedToken: null,
	users: [],
	user: {},
	myInfo: {},
	correct: {},
	tags: [],
	category: {},
	probs: [],
	prob: {},
	isAddTag: false,
	isAddProb: false,
	isAddNotice: false,
	isAddShop: false,
	isChangePassword: true,
	items: [],
	notice: [],
	files: [],
	shop: [],
	product: {},
	isAddAuction: false,
	auction: [],
	settings: [],
}

export default state
